package com.aws.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Employee")
public class Employee {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String employeeId;
    @DynamoDBAttribute
    private String employeeName;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private Department department;
}
